### ISSUE TITLE
Unable to change bluecherry UID/GID at runtime

### ISSUE THREAD

**Issue by gmckeown** [bluecherrydvr/bluecherry-docker#14]
Looks like you've got support for setting the UID and GID for the bluecherry user and group at image build time, but not at runtime?

The docker-compose hints at the possibility of setting these via some commented-out environment variable statements.

Would adding basic support just be a case of adding something blunt like this to the start of the entrypoint.sh script:
```bash
if [ ! -z "$BLUECHERRY_GROUP_ID" ] && [ ! -z "$BLUECHERRY_USER_ID" ]; then
        echo "> Change user and group IDs"
        groupmod -g $BLUECHERRY_GROUP_ID bluecherry
        usermod -u $BLUECHERRY_USER_ID -g $BLUECHERRY_GROUP_ID bluecherry
        chown -R bluecherry:bluecherry /tmp
fi
```
and setting the appropriate lines in the .env file:
```bash
# UID/GID to run bluecherry user as. If you want to access recordings from the host, it is
# recommended to set them the same as a user/group that you want access to read it.
# run `id $(whoami)` to find the UID/GID of your user
BLUECHERRY_GROUP_ID=1002
BLUECHERRY_USER_ID=1002
```

Or are there other dependencies that need to be taken care of?

**Comment by curtishall** [comment]
See the scripts/install.sh for an automated process.
