### ISSUE TITLE
Provided MySQL admin credentials are incorrect

### ISSUE THREAD

**Issue by andreaslink-de** [bluecherrydvr/bluecherry-docker#16]
Tried to run bluecherry using docker compose, but there seem to be some general problems.

`$MYSQL_ADMIN_PASSWORD` is referenced in "mysql" service, but no ".env" is included, I would assume the section
```
    env_file:
      - ./.env
```
is missing in there in the docker-compose.yaml to be able to read the preset root password, isn't it?

Further on, newest aka latest mysql server does not seem to ger the password in the initial db-setup step as it states:
```
2022-10-22T22:05:36.604622Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
```
So my assumption is, the mysql server has to be initialized differently. As a result of this the documented step `sudo docker-compose run bluecherry bc-database-create` fails as well with the error:
```
+ echo 'show databases'
+ mysql_wrapper -hmysql -uroot
+ echo -e '\n\n\tProvided MySQL admin credentials are incorrect\n'


	Provided MySQL admin credentials are incorrect

++ whoami
+ echo -e 'Please create ~root/.my.cnf with right password like this\n'
Please create ~root/.my.cnf with right password like this

```

Currently I am slightly stuck now as I think my .env has the right details, but all the rest is not correctly defined and will probably not come up as it should, so I was not able to succeed here. Any ideas?

**Comment by curtishall** [comment]
Did you rename dotenv to .env?

I just followed the steps line by line on a clean install and everything worked as expected.

**Comment by andreaslink-de** [comment]
> Did you rename dotenv to .env?
Yes, it is renamed.

But Ok, that surprises me, but I will then retry once again exactly like described. And your SQL in the newest version was also not created with an empty password?

**Comment by curtishall** [comment]
Hold off, I changed to mysql 5.7.  Let me do some more testing, it seemed to work the first time but the second time when I launched the server app it kept respawning.

**Comment by andreaslink-de** [comment]
Thanks Curtis, that sounds more similar to my situation. So, really spinning it all up as described does not work according to my experience.

**Comment by curtishall** [comment]
See the scripts/install.sh for an automated process.
