### ISSUE TITLE
Can't build a docker image with current version v3.1.0-rc6

### ISSUE THREAD

**Issue by mi1985** [bluecherrydvr/bluecherry-docker#17]
Hi
I tried to create a docker image with the current bluecherry version v.3.1.0-rc6. I change the git version in the dockerfile and start the build process. The baseos is still ubutunu 20.04. 

Those are the last critical lines, which failed: 

`++ cat /etc/os-release
++ grep '^ID='
++ grep debian
+ [[ -n '' ]]
++ git describe --dirty --always --long
++ git describe --all
+ echo '#define GIT_REVISION "97293d1-dirty heads/master"'
+ [[ '' == centos* ]]
+ debian/rules debian/control
dpkg-parsechangelog: warning:     debian/changelog(l6): found start of entry where expected more change data or trailer
LINE: bluecherry (3:3.1.0-rc6) focal bionic buster groovy hirsute bullseye; urgency=low
dpkg-parsechangelog: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
sed -e 's/^#focal//' debian/control.in | grep -v '^#' > debian/control
dpkg-parsechangelog: warning:     debian/changelog(l6): found start of entry where expected more change data or trailer
LINE: bluecherry (3:3.1.0-rc6) focal bionic buster groovy hirsute bullseye; urgency=low
dpkg-parsechangelog: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
+ debian/rules clean binary
dpkg-parsechangelog: warning:     debian/changelog(l6): found start of entry where expected more change data or trailer
LINE: bluecherry (3:3.1.0-rc6) focal bionic buster groovy hirsute bullseye; urgency=low
dpkg-parsechangelog: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
dh --parallel clean
dpkg-parsechangelog: warning:     debian/changelog(l6): found start of entry where expected more change data or trailer
LINE: bluecherry (3:3.1.0-rc6) focal bionic buster groovy hirsute bullseye; urgency=low
dpkg-parsechangelog: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
dh: warning: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_auto_clean
dh_auto_clean: warning: Compatibility levels before 9 are deprecated (level 7 in use)
        make -j1 clean
make[1]: Entering directory '/root/bluecherry-apps'
make[2]: Entering directory '/root/bluecherry-apps/misc'
fatal: not a git repository: '/root/bluecherry-apps/misc/libconfig/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libconfig/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libav/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libav/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/pugixml/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/pugixml/.git'
make -C libconfig clean
make[3]: *** No rule to make target 'clean'.  Stop.
make[2]: [BCMK:15: libconfig-clean] Error 2 (ignored)
make[3]: Entering directory '/root/bluecherry-apps/misc/libconfig'
make[3]: Leaving directory '/root/bluecherry-apps/misc/libconfig'
rm libconfig/Makefile
rm: cannot remove 'libconfig/Makefile': No such file or directory
make[2]: [BCMK:16: libconfig-clean] Error 1 (ignored)
make -C libav distclean
make[3]: Entering directory '/root/bluecherry-apps/misc/libav'
make[3]: Leaving directory '/root/bluecherry-apps/misc/libav'
make[3]: *** No rule to make target 'distclean'.  Stop.
make -C pugixml clean
make[2]: [BCMK:124: libav-clean] Error 2 (ignored)
make[3]: *** No rule to make target 'clean'.  Stop.
make[3]: Entering directory '/root/bluecherry-apps/misc/pugixml'
make[3]: Leaving directory '/root/bluecherry-apps/misc/pugixml'
rm pugixml/Makefile
make[2]: [BCMK:152: pugixml-clean] Error 2 (ignored)
rm: cannot remove 'pugixml/Makefile': No such file or directory
rm -rf /root/bluecherry-apps/stage
make[2]: [BCMK:153: pugixml-clean] Error 1 (ignored)
make[2]: Leaving directory '/root/bluecherry-apps/misc'
make[2]: Entering directory '/root/bluecherry-apps/lib'
rm -f bc-core.o bc-utils.o bc-db-core.o bc-db-mysql.o bc-key.o bc-media.o lavf_device.o bc-ptz.o bc-stats.o input_device.o v4l2_device_solo6x10.o stream_elements.o logging.o bc-syslog.o sliding_seq_window.o v4l2_device_tw5864.o v4l2_device_solo6010-dkms.o bc-core.d bc-utils.d bc-db-core.d bc-db-mysql.d bc-key.d bc-media.d lavf_device.d bc-ptz.d bc-stats.d input_device.d v4l2_device_solo6x10.d stream_elements.d logging.d bc-syslog.d sliding_seq_window.d v4l2_device_tw5864.d v4l2_device_solo6010-dkms.d libbluecherry.so.0 libbluecherry.so
make[2]: Leaving directory '/root/bluecherry-apps/lib'
make[2]: Entering directory '/root/bluecherry-apps/server'
rm -f bc-server.o bc-thread.o media_writer.o g723-dec.o bc-detect.o streaming.o rtsp.o signals.o motion_processor.o trigger_processor.o decoder.o encoder.o reencoder.o vaapi.o scaler.o recorder.o motion_handler.o ffmpeg-init.o bt.o status_server.o trigger_server.o substream-thread.o onvif_events.o v3license_server.o v3license_processor.o hls.o bc-api.o bc-server.d bc-thread.d media_writer.d g723-dec.d bc-detect.d streaming.d rtsp.d signals.d motion_processor.d trigger_processor.d decoder.d encoder.d reencoder.d vaapi.d scaler.d recorder.d motion_handler.d ffmpeg-init.d bt.d status_server.d trigger_server.d substream-thread.d onvif_events.d v3license_server.d v3license_processor.d hls.d bc-api.d bc-server
make[2]: Leaving directory '/root/bluecherry-apps/server'
make[2]: Entering directory '/root/bluecherry-apps/utils'
rm -f pelcocmd ptzcmd bc-license licensecmd  *.o
make[2]: Leaving directory '/root/bluecherry-apps/utils'
make[1]: Leaving directory '/root/bluecherry-apps'
   dh_clean
dh_clean: warning: Compatibility levels before 9 are deprecated (level 7 in use)
dh --parallel binary
dpkg-parsechangelog: warning:     debian/changelog(l6): found start of entry where expected more change data or trailer
LINE: bluecherry (3:3.1.0-rc6) focal bionic buster groovy hirsute bullseye; urgency=low
dpkg-parsechangelog: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
dh: warning: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_update_autotools_config
   dh_auto_configure
dh_auto_configure: warning: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_auto_build
dh_auto_build: warning: Compatibility levels before 9 are deprecated (level 7 in use)
        make -j1
make[1]: Entering directory '/root/bluecherry-apps'
make[2]: Entering directory '/root/bluecherry-apps/misc'
fatal: not a git repository: '/root/bluecherry-apps/misc/libconfig/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libconfig/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libav/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/libav/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/pugixml/.git'
fatal: not a git repository: '/root/bluecherry-apps/misc/pugixml/.git'
cd libconfig/ && autoreconf -if
autoreconf: 'configure.ac' or 'configure.in' is required
make[2]: *** [BCMK:19: libconfig/Makefile] Error 1
make[2]: Leaving directory '/root/bluecherry-apps/misc'
make[1]: *** [Makefile:20: misc/all] Error 2
make[1]: Leaving directory '/root/bluecherry-apps'
dh_auto_build: error: make -j1 returned exit code 2
make: *** [debian/rules:12: binary] Error 25
The command '/bin/sh -c cd bluecherry-apps  && ./scripts/build_pkg_native.sh' returned a non-zero code: 2
`

Is it possible to get a new docker file or may I ask to upload a prebuild docker file which current version 3.1.0-rc6?
Many thanks

**Comment by curtishall** [comment]
New images updated for -rc8.  Also see the scripts/install.sh for an automated process.
