### ISSUE TITLE
TZ in not properly configured during build

### ISSUE THREAD

**Issue by astafyev** [bluecherrydvr/bluecherry-docker#6]
I configured 
`TZ=Europe/Kiev`
in .env before build but have 
```
# cat /etc/timezone
Etc/UTC
# ls -l /etc/localtime 
/etc/localtime -> /usr/share/zoneinfo/Etc/UTC
```

in resulting container.
It seems that TZ variable is not used during build.

**Comment by curtishall** [comment]
I believe this is fixed.  The docker will use the local timezone data set on your server.
