### ISSUE TITLE
Wrong path to recordings

### ISSUE THREAD

**Issue by astafyev** [bluecherrydvr/bluecherry-docker#7]
Docker file implies recordings are placed in /recordings folder in  container, but instead they go to /var/lib/bluecherry/recordings.
Permissions on container start are also applied to /recordings. As a result, on Playback page I can see a list of events, but when I choose one, I don't see any preview. I access log I see 404 error:
`"GET /media/request?mode=screenshot&device_id=11&id=11 HTTP/1.1" 404 409 "https://192.168.1.1:7001/playback"`
After I do
`ln -s /var/lib/bluecherry/recordings/ /recordings`
I can see preview, but when I try to play it, I get
`Error loading this resource`
in browser and in Apache logs:
`"GET /media/stream-mp4?id=65 HTTP/1.1" 500 351 "https://192.168.1.1:7001/playback"`
In browser's console I see
` Failed to load resource: the server responded with a status of 500 (Internal Server Error - unsupported codec in video file)`
It may be related that stream format is in h265.

**Comment by curtishall** [comment]
Thanks, the latest commit (26bbb5636944ead2a858eb406e58a67d3a96b2c1) should resolve this

**Comment by sicada** [comment]
I think line 21 of the supervisord.conf file also still needs to be updated? It still refers to the old /recordings path:

`command=chown bluecherry:bluecherry /recordings`

**Comment by curtishall** [comment]
New images updated for -rc8.  Also see the scripts/install.sh for an automated process.
