### ISSUE TITLE
Timezone is set to UTC

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-docker#9]
https://forums.bluecherrydvr.com/t/video-playback-oddities/

**Comment by aaronouthier** [comment]
For context, this occurs in the Docker Image. The Server Timezone is configured to US Pacific (PST-8PDT). I am the one who reported the bug in the BlueCherry forums.

**Comment by curtishall** [comment]
Fixed in the new automated scripts (scripts/install.sh)
